[package]
name = "graphics_test"
version = "0.1.0"
edition = "2021"

[dependencies]


egui = "*"
wgpu = "*"
eframe = "*"

glow = "*"
image = "*"

mycelium-bitfield = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
